# Generated by Django 4.1.5 on 2023-02-06 08:27

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0002_photo_imagefile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="photo",
            name="imagefile",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=pathlib.PureWindowsPath(
                    "C:/Users/강지윤/workspace/django/MyPhoto/media"
                ),
            ),
        ),
        
    ]
