# Generated by Django 4.1.5 on 2023-02-07 00:22

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="imagefile",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=pathlib.PureWindowsPath(
                    "C:/Users/강지윤/workspace/django/mytodo/media"
                ),
            ),
        ),
    ]
