# Generated by Django 4.1.5 on 2023-02-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_todo_imagefile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="imagefile",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="C:\\Users\\강지윤\\workspace\\django\\mytodo\\media",
            ),
        ),
    ]
