# Generated by Django 4.1.5 on 2023-02-09 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bbs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="board",
            new_name="board_id",
        ),
    ]
